### ISSUE TITLE
Occurs AttributeError: 'NoneType' object has no attribute 'encode' error when using a2wsgi with keystonemiddleware

### ISSUE THREAD

**Issue by frankming123** [abersheeran/a2wsgi#39]
Hi guy,
  I try to transfer keystonemiddleware to asgi middleware with a2wsgi module. However, it occurs AttributeError when I send a request. Errors are as follows:

```shell
INFO:     ::ffff:10.244.0.1:58980 - "GET /v1/flow_types HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/scorch/middlewares.py", line 36, in __call__
    await app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/a2wsgi/wsgi.py", line 157, in __call__
    return await responder(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/a2wsgi/wsgi.py", line 191, in __call__
    await self.loop.run_in_executor(
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/a2wsgi/wsgi.py", line 244, in wsgi
    for chunk in self.app(environ, start_response):
  File "/usr/local/lib/python3.9/site-packages/webob/dec.py", line 129, in __call__
    resp = self.call_func(req, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/webob/dec.py", line 193, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/keystonemiddleware/auth_token/__init__.py", line 340, in __call__
    response = req.get_response(self._app)
  File "/usr/local/lib/python3.9/site-packages/webob/request.py", line 1313, in send
    status, headers, app_iter = self.call_application(
  File "/usr/local/lib/python3.9/site-packages/webob/request.py", line 1281, in call_application
    output.extend(app_iter)
  File "/usr/local/lib/python3.9/site-packages/a2wsgi/asgi.py", line 207, in __call__
    asgi_task = self.start_asgi_app(environ)
  File "/usr/local/lib/python3.9/site-packages/a2wsgi/asgi.py", line 194, in start_asgi_app
    self.app(build_scope(environ), self.asgi_receive, self.asgi_send),
  File "/usr/local/lib/python3.9/site-packages/a2wsgi/asgi.py", line 75, in build_scope
    headers = [
  File "/usr/local/lib/python3.9/site-packages/a2wsgi/asgi.py", line 76, in <listcomp>
    (key.lower().replace("_", "-").encode("latin-1"), value.encode("latin-1"))
AttributeError: 'NoneType' object has no attribute 'encode'
```

Afterwards, I tried to troubleshoot it and found some value of environ variable is None, such as `('OPENSTACK_SYSTEM_SCOPE', None), ('X_DOMAIN_ID', None), ('X_DOMAIN_NAME', None)`. a2wsgi try to handle some headers in environ at build_scope function of asgi.py file. Using value.encode("latin-1") statement while value is None leads to the error finally.

So, could you please fix this problem? I will wait for you to solve this and produce new package. Thinks.

**Comment by hasansezertasan** [comment]
Can you share a MRE?

**Comment by abersheeran** [comment]
Can you paste this Environ over? a2wsgi will only convert variables starting with HTTP_, and the None ones you mentioned should not enter this branch.

https://github.com/abersheeran/a2wsgi/blob/4833fe444a86e676b50c93e4bc4aee335ce93a67/a2wsgi/asgi.py#L73-L89

**Comment by abersheeran** [comment]
Since I can't verify it, I'm temporarily closing this PR. If you can provide more detailed information, please reopen it.

**Comment by frankming123** [comment]
> Since I can't verify it, I'm temporarily closing this PR. If you can provide more detailed information, please reopen it.

Sorry I don't visit github often and almost forgot such thing. I try to debug environ variale with `[print(k, v) for k, v in environ.items()]` statement aften entering into *build_scope* function.

Outputs about debug are as follows:

```shell
asgi.scope {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('::ffff:10.244.0.86', 8005), 'client': ('::ffff:10.244.0.1', 56160), 'scheme': 'http', 'method': 'GET', 'root_path': '', 'path': '/v1/packages/', 'raw_path': b'/v1/packages/', 'query_string': b'all_projects=true', 'headers': [(b'host', b'scorch.kube-system.svc.cluster.local'), (b'x-request-id', b'd7c108e3f0e9d1c69d46ce1593f00879'), (b'x-real-ip', b'10.15.80.106'), (b'x-forwarded-for', b'10.15.80.106'), (b'x-forwarded-host', b'scorch.kube-system.svc.cluster.local'), (b'x-forwarded-port', b'10080'), (b'x-forwarded-proto', b'http'), (b'x-forwarded-scheme', b'http'), (b'x-scheme', b'http'), (b'x-auth-token', b'gAAAAABlp4Gwa6Kz9ZzhlrhjrKZ5H0JDZZFF7KNuf94In1wGn377819Rlx-p4eT6pBZnsT5ppr5ifzdI5Slbi4SWwF7IKjDiWv-fozfCvQKJ-RXmYJbpBo4gxkoaRlwYbnTJRum-JixTqmFWPu_6h4nK48gLjGAQPX3YYQYVBB4N5aHynqaj89A'), (b'user-agent', b'PostmanRuntime/7.36.0'), (b'accept', b'*/*'), (b'cache-control', b'no-cache'), (b'postman-token', b'aac4d7f1-433f-4089-81e2-9802c895dd9a'), (b'accept-encoding', b'gzip, deflate, br')], 'state': {}, 'app': <fastapi.applications.FastAPI object at 0x7f385ab74ee0>}
REQUEST_METHOD GET
SCRIPT_NAME
PATH_INFO /v1/packages/
QUERY_STRING all_projects=true
SERVER_PROTOCOL HTTP/1.1
wsgi.version (1, 0)
wsgi.url_scheme http
wsgi.input <a2wsgi.wsgi.Body object at 0x7f3852388a90>
wsgi.errors <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
wsgi.multithread True
wsgi.multiprocess True
wsgi.run_once False
SERVER_NAME ::ffff:10.244.0.86
SERVER_PORT 8005
REMOTE_ADDR ::ffff:10.244.0.1
HTTP_HOST scorch.kube-system.svc.cluster.local
HTTP_X_REQUEST_ID d7c108e3f0e9d1c69d46ce1593f00879
HTTP_X_REAL_IP 10.15.80.106
HTTP_X_FORWARDED_FOR 10.15.80.106
HTTP_X_FORWARDED_HOST scorch.kube-system.svc.cluster.local
HTTP_X_FORWARDED_PORT 10080
HTTP_X_FORWARDED_PROTO http
HTTP_X_FORWARDED_SCHEME http
HTTP_X_SCHEME http
HTTP_X_AUTH_TOKEN gAAAAABlp4Gwa6Kz9ZzhlrhjrKZ5H0JDZZFF7KNuf94In1wGn377819Rlx-p4eT6pBZnsT5ppr5ifzdI5Slbi4SWwF7IKjDiWv-fozfCvQKJ-RXmYJbpBo4gxkoaRlwYbnTJRum-JixTqmFWPu_6h4nK48gLjGAQPX3YYQYVBB4N5aHynqaj89A
HTTP_USER_AGENT PostmanRuntime/7.36.0
HTTP_ACCEPT */*
HTTP_CACHE_CONTROL no-cache
HTTP_POSTMAN_TOKEN aac4d7f1-433f-4089-81e2-9802c895dd9a
HTTP_ACCEPT_ENCODING gzip, deflate, br
webob.adhoc_attrs {'response': <_AuthTokenResponse at 0x7f3851a734c0 200 OK>}
HTTP_X_IDENTITY_STATUS Confirmed
keystone.token_auth <keystonemiddleware.auth_token._user_plugin.UserAuthPlugin object at 0x7f3851a95880>
HTTP_X_ROLES reader,_member_,user,member,admin
HTTP_OPENSTACK_SYSTEM_SCOPE None
HTTP_X_DOMAIN_ID None
HTTP_X_DOMAIN_NAME None
HTTP_X_PROJECT_ID 43406fbacc7d4a4b816e358a825978f4
HTTP_X_PROJECT_NAME admin
HTTP_X_PROJECT_DOMAIN_ID default
HTTP_X_PROJECT_DOMAIN_NAME Default
HTTP_X_USER_ID a92de093b2464a6e9fbc7feac1b08835
HTTP_X_USER_NAME admin
HTTP_X_USER_DOMAIN_ID default
HTTP_X_USER_DOMAIN_NAME Default
HTTP_X_IS_ADMIN_PROJECT True
HTTP_X_ROLE reader,_member_,user,member,admin
HTTP_X_USER admin
HTTP_X_TENANT_ID 43406fbacc7d4a4b816e358a825978f4
HTTP_X_TENANT_NAME admin
HTTP_X_TENANT admin
```

Apparently, there are three environ variable contains *None* value: HTTP_OPENSTACK_SYSTEM_SCOPE, HTTP_X_DOMAIN_ID and HTTP_X_DOMAIN_NAME. I know the variables are customized and occur in only a few specified situations. Howerer, I still think it is necessary to judge value's type before `value.encode("latin-1")` since it raise AttributeError if value is None. Many thanks.

**Comment by frankming123** [comment]
@abersheeran By the way, where is reopen button? I can't see it when commenting. Does it require me to be a contributor?

**Comment by abersheeran** [comment]
None should not be allowed for key-value pairs starting with HTTP, what WSGI SERVER are you using？Gunicorn？or Waitress？
